### ISSUE TITLE
想请教您

### ISSUE THREAD

**Issue by cuirongjin** [huijiewei/yii2-jsqr#1]
您这个可以在手机上使用吗就是类似于那种扫一扫的功能

**Comment by huijiewei** [comment]
手机浏览器，我测试过Sarafi 可以的，你可以用各种手机浏览器打开demo页面测试

**Comment by cuirongjin** [comment]
哥我还行问您这个可以在vue中引入吗，具体的是怎么做的呀 那个min.js如何在vue中使用呢

**Comment by huijiewei** [comment]
vue 已经有现成的实现了
https://github.com/pulilab/vue-qr-reader
